### ISSUE TITLE
tado° Ecological Footprint Analysis

### ISSUE THREAD

**Issue by MarielaSassi** [tadodotcom/Sustainability-Team#21]
# Description
This was already done in 2020, but we want to analyse what was done and maybe have a professional assessment.

# Related links
Sent by Stefanie:
https://docs.google.com/spreadsheets/d/1kCaPf_VlwCT2J5YXIbbMwlTkBJ8b-5hVya48lYFiIvU/edit#gid=0
https://docs.google.com/document/d/1QSp3SeBpHBUdyOmYyhC2EKrnZQDI3oL3RmqvY61ofSU/edit#bookmark=id.gcr9hhkwt93i

# Any other notes?

**Comment by MarielaSassi** [comment]
Check shared drive folder Energy Audit / Life cycle assessment.

**Comment by jonashuber** [comment]
Mariela:
- Will check the rough costs
- Will talk to Daniel K. afterwards

**Comment by soleilhuynh** [comment]
https://res.cloudinary.com/dhpk1grmy/image/upload/v1593595335/Guidelines/lfca_unternehmens_leitfaden-2_uaysnu.pdf

**Comment by soleilhuynh** [comment]
https://ecovadis.com/plans-pricing/

**Comment by MarielaSassi** [comment]
> Hi sustainability team,
> Thanks for all your work! 
> 
> I guess you know the initiative [Leaders for Climate Action](https://lfca.earth/ALL_de/)? Do you know if tado management was approached to join or considered joining? (Many startups from the German ecosystem have already[ joined](https://lfca.earth/ALL_de/companies))
> 
> They also launched this[ campaign ](https://tfca.earth/de_de/)recently (climate actions in less than 5 minutes). Maybe its worth sharing it with the company.
> 
> Best
> Till

This, I believe it's a separate topic, it's a nice website with cool information (last link at least, the others are 404 now).
But the carbon footprint calculator I found there was just for individuals.
It tells in one deck how to measure the carbon footprint of your company and I believe it's more or less what was already done, but now the idea is to have a third company looking at tado and doing a professional assessment, if possible.

**Comment by MarielaSassi** [comment]
> https://res.cloudinary.com/dhpk1grmy/image/upload/v1593595335/Guidelines/lfca_unternehmens_leitfaden-2_uaysnu.pdf

I don't understand it entirely as it is in Germany, but it looks like a list of things to do to improve the carbon footprint, correct? It's not a company providing the carbon footprint assessment service.

**Comment by MarielaSassi** [comment]
- [ ] Look into this: https://ec.europa.eu/environment/emas/join_emas/how_does_it_work_step0_en.htm
Maybe open a new issue

**Comment by MarielaSassi** [comment]
E-mail from Daniel K.:
a) Write down some context/explanation (i.e. a) a few more bullets on what it is, 
b) why it makes sense for us/ what we get out of it,
c) how much it roughly costs,
d) what the next steps would be
e) to get a management decision on it.
Would try to keep this lean however, i.e. not invest too much time into this and keep it high-level (as the actual work then starts when there is a management "go")."

**Comment by MarielaSassi** [comment]
https://docs.google.com/presentation/d/1j7oiopZwcrOGPz-I5wJUfuPvJi4iHH9ZgtmA4LD_Mbc/edit?usp=sharing

**Comment by MarielaSassi** [comment]
I'll close this issue, since it will be presented to management together with CSR.
