### ISSUE TITLE
Sustainability Newsletter July

### ISSUE THREAD

**Issue by soleilhuynh** [tadodotcom/Sustainability-Team#26]
# Description
# Objectives:
Keep the company updated relating to sustainability activities
Engage the employees to act sustainability at work and in daily life

1. Actions of Departments Department in the June Newsletter: Office Manager
2. Entertainment content
3. Call for action
4. Sustainability Team Update
5. Frequent content: Black Board + email address

# Being sustainable in business at tado
Department: Marketing
# Related links https://docs.google.com/presentation/d/1CB576ajaKfhk8p5UBe15xoaCSxAn4Q9iYm1r8YGABZA/edit#slide=id.gd1796cfa44_0_14

# Any other notes?

**Comment by MarielaSassi** [comment]
https://github.com/tadodotcom/Sustainability-Team/issues/24#issuecomment-868355617

**Comment by MikeNiedermayr** [comment]
## Possible links to share with the newsletter:

### Calculate your own carbon footprint (one person or family)
https://you.climatepartner.com/en/

### Climate map
Find Climate projects worldwide
https://www.climatepartner.com/en/climatemap/offset-projects

Find climate neutral companies and services
https://www.climatepartner.com/en/climatemap/companies
