### ISSUE TITLE
Tracking tool: Implement nudging idea from one of LMU's presentation

### ISSUE THREAD

**Issue by MarielaSassi** [tadodotcom/Sustainability-Team#28]
# Description
Have an e-mail with a progress bar of each topic to show all tadonauts which Sustainability projects are ongoing and their progress

# Related links
NA

# Any other notes?
NA

**Comment by MarielaSassi** [comment]
@jonashuber and I talked about this and we agreed that it's better to just add a link to this Zenhub board in the Newsletter, so whoever is interested in the topics and the progress can check here.
It would be extra work to maintain progress bars with the topics in some dashboard, for instance, and as Jonas said, we could use the time better, to do the regular work and to do sustainability work.

So, do you agree to just add the link to this Zenhub board in the newsletter? @soleilhuynh @MikeNiedermayr @GeertPaelinck

**Comment by MarielaSassi** [comment]
Related to #26

**Comment by soleilhuynh** [comment]
I think it is a good idea. thank you team

**Comment by GeertPaelinck** [comment]
@soleilhuynh add the link to the newsletter and close issue
