### ISSUE TITLE
Newsletter June

### ISSUE THREAD

**Issue by soleilhuynh** [tadodotcom/Sustainability-Team#3]
**Objectives:** 
Keep the company updated relating to sustainability activities
Engage the employees to act sustainability at work and in daily life

**1. Actions of Departments** Department in the June Newsletter: Office Manager
**2. Entertainment content
3. Call for action
4. Sustainability Team Update
5. Frequent content: Black Board + email address**

**Comment by soleilhuynh** [comment]
https://docs.google.com/presentation/d/1ueKGovkwNugO6UALmWVVjBw8Z5sdHMQBhSXkMMaR980/edit#slide=id.gd1796cfa44_0_14

**Comment by GeertPaelinck** [comment]
Idea for article: How to keep your home cool sustainable

**Comment by GeertPaelinck** [comment]
@MikeNiedermayr search for fitting meme
